name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # 或者指定你本地使用的具体版本

      # 2. 设置 Node.js 环境并使用 pnpm 缓存
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      # 3. 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 4. 执行静态导出
      - name: Static HTML export
        run: pnpm nuxi generate

      # 5. 解决 GitHub Pages 路径过滤问题
      - name: Add .nojekyll
        run: touch .output/public/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4